/*
create user C##BAITHIHTTT1 identified by C##BAITHIHTTT1;
grant connect, resource, oem_monitor, dba to C##BAITHIHTTT1;
grant create synonym, create any table to C##BAITHIHTTT1;
*/

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

CREATE TABLE C##BAITHIHTTT1.XE
(
    MAXE VARCHAR2(3) NOT NULL PRIMARY KEY,
    BIENKS VARCHAR2(10),
    MATUYEN VARCHAR2(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
);

INSERT INTO C##BAITHIHTTT1.XE(MAXE, BIENKS, MATUYEN, SOGHET1, SOGHET2)
VALUES('X01', '52LD-4393', 'T11A', 20, 20);
INSERT INTO C##BAITHIHTTT1.XE(MAXE, BIENKS, MATUYEN, SOGHET1, SOGHET2)
VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO C##BAITHIHTTT1.XE(MAXE, BIENKS, MATUYEN, SOGHET1, SOGHET2)
VALUES('X03', '55LD-6850', 'T06F', 15, 15);

CREATE TABLE C##BAITHIHTTT1.TUYEN
(
    MATUYEN VARCHAR2(4) NOT NULL PRIMARY KEY,
    BENDAU VARCHAR2(3) NOT NULL,
    BENCUOI VARCHAR2(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
);

INSERT INTO C##BAITHIHTTT1.TUYEN(MATUYEN, BENDAU, BENCUOI, GIATUYEN, NGXB, TGDK)
VALUES ('T11A', 'SG', 'DL', 210000, TO_DATE('26/12/2016','DD/MM/YYYY'), 6);
INSERT INTO C##BAITHIHTTT1.TUYEN(MATUYEN, BENDAU, BENCUOI, GIATUYEN, NGXB, TGDK)
VALUES ('T32D', 'PT', 'SG', 120000, TO_DATE('30/12/2016','DD/MM/YYYY'), 4);
INSERT INTO C##BAITHIHTTT1.TUYEN(MATUYEN, BENDAU, BENCUOI, GIATUYEN, NGXB, TGDK)
VALUES ('T06F', 'NT', 'DNG', 225000, TO_DATE('02/01/2017', 'DD/MM/YYYY'), 7);

CREATE TABLE C##BAITHIHTTT1.KHACH
(
    MAKH VARCHAR2(4) NOT NULL PRIMARY KEY,
    HOTEN VARCHAR2(100),
    GIOITINH VARCHAR2(5),
    CMND NUMBER(12)
);

INSERT INTO C##BAITHIHTTT1.KHACH(MAKH, HOTEN, GIOITINH, CMND)
VALUES('KH01', 'Lâm Văn Bền', 'Nam', '655615896');
INSERT INTO C##BAITHIHTTT1.KHACH(MAKH, HOTEN, GIOITINH, CMND)
VALUES('KH02', 'Dương Thị Lục', 'Nữ', '2756486426');
INSERT INTO C##BAITHIHTTT1.KHACH(MAKH, HOTEN, GIOITINH, CMND)
VALUES('KH03', 'Hoàng Thanh Tùng', 'Nam', '456889143');

CREATE TABLE C##BAITHIHTTT1.VEXE
(
    MATUYEN VARCHAR(4) NOT NULL,
    MAKH VARCHAR(4) NOT NULL,
    NGMUA DATE NOT NULL,
    GIAVE DECIMAL,
    CONSTRAINT VX_PK PRIMARY KEY(MATUYEN,MAKH,NGMUA)
);

INSERT INTO C##BAITHIHTTT1.VEXE(MATUYEN, MAKH, NGMUA, GIAVE)
VALUES('T11A', 'KH01', TO_DATE('20/12/2016', 'DD/MM/YYYY'), 210000);
INSERT INTO C##BAITHIHTTT1.VEXE(MATUYEN, MAKH, NGMUA, GIAVE)
VALUES('T32D', 'KH02', TO_DATE('25/12/2016', 'DD/MM/YYYY'), 144000);
INSERT INTO C##BAITHIHTTT1.VEXE(MATUYEN, MAKH, NGMUA, GIAVE)
VALUES('T06F', 'KH03', TO_DATE('30/12/2016', 'DD/MM/YYYY'), 270000);

/*
DROP TABLE VEXE;
DROP TABLE XE;
DROP TABLE KHACH;
DROP TABLE TUYEN;
DELETE FROM VEXE;
*/
------KHOA NGOAI
ALTER TABLE C##BAITHIHTTT1.XE
ADD CONSTRAINT XE_FN FOREIGN KEY(MATUYEN) REFERENCES C##BAITHIHTTT1.TUYEN(MATUYEN);
ALTER TABLE C##BAITHIHTTT1.VEXE
ADD CONSTRAINT VX_FN_1 FOREIGN KEY(MATUYEN) REFERENCES C##BAITHIHTTT1.TUYEN(MATUYEN);
ALTER TABLE C##BAITHIHTTT1.VEXE
ADD CONSTRAINT FK_FN_2 FOREIGN KEY(MAKH) REFERENCES C##BAITHIHTTT1.KHACH(MAKH);
------3
ALTER TABLE C##BAITHIHTTT1.TUYEN 
ADD CONSTRAINT T_CHECK_CAU3 CHECK (TGDK > 5 AND GIATUYEN > 200000)
ENABLE NOVALIDATE;
------4
CREATE OR REPLACE TRIGGER C##BAITHIHTTT1.TRIGGER_CAU4
BEFORE INSERT OR UPDATE OF MATUYEN ON C##BAITHIHTTT1.VEXE
FOR EACH ROW
DECLARE 
NG_XB DATE;
GIA_TUYEN DECIMAL;
BEGIN
    SELECT NGXB, GIATUYEN INTO NG_XB, GIA_TUYEN
    FROM C##BAITHIHTTT1.TUYEN
    WHERE MATUYEN = :NEW.MATUYEN;
    
    IF TO_DATE(NG_XB, 'DD/MM/YYYY') BETWEEN TO_DATE('29/12/2016', 'DD/MM/YYYY') AND TO_DATE('05/01/2017', 'DD/MM/YYYY') THEN
        BEGIN
            :NEW.GIAVE := GIA_TUYEN*1.2;
        END;
    END IF;
END;

------5
SELECT *
FROM C##BAITHIHTTT1.VEXE
WHERE EXTRACT(MONTH FROM NGMUA) = 12 
ORDER BY GIAVE DESC;
------6
SELECT MATUYEN
FROM C##BAITHIHTTT1.VEXE
WHERE EXTRACT(YEAR FROM NGMUA) = 2016 
GROUP BY MATUYEN
HAVING COUNT(MATUYEN) <= ALL(  SELECT COUNT(MATUYEN)
                            FROM C##BAITHIHTTT1.VEXE
                            WHERE EXTRACT(YEAR FROM NGMUA) = 2016 
                            GROUP BY MATUYEN
                            );
------7
SELECT MATUYEN
FROM C##BAITHIHTTT1.KHACH K JOIN C##BAITHIHTTT1.VEXE VX ON K.MAKH = VX.MAKH
WHERE GIOITINH = 'Nam'
INTERSECT
SELECT MATUYEN
FROM C##BAITHIHTTT1.KHACH K JOIN C##BAITHIHTTT1.VEXE VX ON K.MAKH = VX.MAKH
WHERE GIOITINH = 'Nữ';
------8
SELECT *
FROM C##BAITHIHTTT1.KHACH K
WHERE GIOITINH = 'Nữ' AND NOT EXISTS (SELECT *
                                        FROM C##BAITHIHTTT1.TUYEN T
                                        WHERE NOT EXISTS(   SELECT *
                                                            FROM C##BAITHIHTTT1.VEXE VX
                                                            WHERE VX.MATUYEN = T.MATUYEN AND VX.MAKH = K.MAKH
                                                            )
                                    );