/*
create user C##BAITHIHTTT3 identified by C##BAITHIHTTT3;
grant connect, resource, oem_monitor, dba to C##BAITHIHTTT3;
grant create synonym, create any table to C##BAITHIHTTT3;
*/

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

CREATE TABLE C##BAITHIHTTT3.HANGHANGKHONG
(
    MAHANG VARCHAR2(4) NOT NULL PRIMARY KEY,
    TENHANG VARCHAR2(50),
    NGTL DATE,
    DUONGBAY NUMBER
);

INSERT INTO C##BAITHIHTTT3.HANGHANGKHONG(MAHANG, TENHANG, NGTL, DUONGBAY)
VALUES('VN', 'Vietnam Airlines', TO_DATE('15/01/1956','DD/MM/YYYY'), 52);
INSERT INTO C##BAITHIHTTT3.HANGHANGKHONG(MAHANG, TENHANG, NGTL, DUONGBAY)
VALUES('VJ', 'Vietjet Air', TO_DATE('25/12/2011', 'DD/MM/YYYY'), 33);
INSERT INTO C##BAITHIHTTT3.HANGHANGKHONG(MAHANG, TENHANG, NGTL, DUONGBAY)
VALUES('BL', 'Jetstar Pacific Airlines', TO_dATE('01/12/1990', 'DD/MM/YYYY'), 13);

CREATE TABLE C##BAITHIHTTT3.CHUYENBAY
(
    MACB VARCHAR2(5) NOT NULL PRIMARY KEY,
    MAHANG VARCHAR2(4),
    XUATPHAT VARCHAR2(100) NOT NULL,
    DIEMDEN VARCHAR2(100) NOT NULL,
    BATDAU TIMESTAMP NOT NULL,
    TGBAY NUMBER(4, 2)
);
INSERT INTO C##BAITHIHTTT3.CHUYENBAY (MACB, MAHANG, XUATPHAT, DIEMDEN, BATDAU, TGBAY)
VALUES('VN550', 'VN', 'TP.HCM', 'Singapore', TIMESTAMP'2015-12-20 13:15:00', 2);
INSERT INTO C##BAITHIHTTT3.CHUYENBAY (MACB, MAHANG, XUATPHAT, DIEMDEN, BATDAU, TGBAY)
VALUES ('VJ331', 'VJ', 'Đà Nẵng', 'Vinh', TIMESTAMP'2015-12-28 22:30:00', 1);
INSERT INTO C##BAITHIHTTT3.CHUYENBAY (MACB, MAHANG, XUATPHAT, DIEMDEN, BATDAU, TGBAY)
VALUES ('BL696', 'BL', 'TP. HCM', 'Đà Lạt', TIMESTAMP'2015-12-24 06:00:00', 0.5);

CREATE TABLE C##BAITHIHTTT3.NHANVIEN
(
    MANV VARCHAR(4) NOT NULL PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(5),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR(50)
);
INSERT INTO C##BAITHIHTTT3.NHANVIEN(MANV, HOTEN, GIOITINH, NGSINH, NGVL, CHUYENMON)
VALUES('NV01', 'Lâm Văn Bền', 'Nam', TO_DATE('10/09/1978', 'DD/MM/YYYY'), TO_DATE('05/06/2000', 'DD/MM/YYYY'), 'Phi công');
INSERT INTO C##BAITHIHTTT3.NHANVIEN(MANV, HOTEN, GIOITINH, NGSINH, NGVL, CHUYENMON)
VALUES('NV02', 'Dương Thị Lục', 'Nữ', TO_DATE('22/03/1989', 'DD/MM/YYYY'), TO_DATE('12/11/2013', 'DD/MM/YYYY'), 'Tiếp viên');
INSERT INTO C##BAITHIHTTT3.NHANVIEN(MANV, HOTEN, GIOITINH, NGSINH, NGVL, CHUYENMON)
VALUES('NV03', 'Hoàng Thanh Tùng', 'Nam', TO_DATE('29/07/1983', 'DD/MM/YYYY'), TO_DATE('11/04/2007', 'DD/MM/YYYY'), 'Tiếp viên');

CREATE TABLE C##BAITHIHTTT3.PHANCONG
(
    MACB VARCHAR2(5) NOT NULL,
    MANV VARCHAR2(4) NOT NULL,
    NHIEMVU VARCHAR2(50),
        CONSTRAINT PC_PK PRIMARY KEY (MACB, MANV)
);
INSERT INTO C##BAITHIHTTT3.PHANCONG(MACB, MANV, NHIEMVU)
VALUES('VN550', 'NV01', 'Cơ trưởng');
INSERT INTO C##BAITHIHTTT3.PHANCONG(MACB, MANV, NHIEMVU)
VALUES('VN550', 'NV02', 'Tiếp viên');
INSERT INTO C##BAITHIHTTT3.PHANCONG(MACB, MANV, NHIEMVU)
VALUES('BL696', 'NV03', 'Tiếp viên trưởng');
------KHOANGOAI
ALTER TABLE C##BAITHIHTTT3.CHUYENBAY
ADD CONSTRAINT CB_FK FOREIGN KEY (MAHANG) REFERENCES C##BAITHIHTTT3.HANGHANGKHONG(MAHANG);
ALTER TABLE C##BAITHIHTTT3.PHANCONG
ADD CONSTRAINT PC_FK_1 FOREIGN KEY (MACB) REFERENCES C##BAITHIHTTT3.CHUYENBAY (MACB);
ALTER TABLE C##BAITHIHTTT3.PHANCONG
ADD CONSTRAINT PC_FK_2 FOREIGN KEY (MANV) REFERENCES C##BAITHIHTTT3.NHANVIEN (MANV);

------3
ALTER TABLE C##BAITHIHTTT3.NHANVIEN
ADD CONSTRAINT NV_CHECK CHECK (CHUYENMON IN('Phicông','Tiếp viên'))
ENABLE NOVALIDATE;
/*
CREATE OR REPLACE TRIGGER TRIGGER_CAU3
BEFORE INSERT OR UPDATE OF CHUYENMON ON NHANVIEN
FOR EACH ROW
BEGIN
    IF :NEW.CHUYENMON NOT IN ('Phi công', 'Tiếp viên') THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20001, 'Chuyên môn của nhân viên chỉ được nhận giá trị là ‘Phi công’ hoặc ‘Tiếp viên’');
        END;
    END IF;
    EXCEPTION WHEN OTHERS THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR');
        END;
END;
*/
-----4
CREATE OR REPLACE TRIGGER C##BAITHIHTTT3.TRIGGER_CAU4
BEFORE INSERT OR UPDATE OF BATDAU ON C##BAITHIHTTT3.CHUYENBAY
FOR EACH ROW
DECLARE
    ESTABLISHED DATE;
BEGIN
    SELECT NGTL INTO ESTABLISHED
    FROM C##BAITHIHTTT3.HANGHANGKHONG
    WHERE MAHANG = :NEW.MAHANG;
    
    IF TRUNC(:NEW.BATDAU) < TRUNC(ESTABLISHED) THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20001, 'Ngày bắt đầu chuyến bay luôn lớn hơn ngày thành lập hãng hàng không quản lý chuyến bay đó.');
        END;
    END IF;
    EXCEPTION WHEN OTHERS THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR');
        END;
END;
------5
SELECT *
FROM C##BAITHIHTTT3.NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH) = 7;
------6
SELECT CB.MACB, CB.MAHANG, CB.XUATPHAT, CB.DIEMDEN, CB.BATDAU, CB.TGBAY
FROM C##BAITHIHTTT3.CHUYENBAY CB JOIN C##BAITHIHTTT3.PHANCONG PC ON CB.MACB = PC.MACB
GROUP BY CB.MACB, CB.MAHANG, CB.XUATPHAT, CB.DIEMDEN, CB.BATDAU, CB.TGBAY
HAVING COUNT(MANV) >= ALL (SELECT COUNT(MANV)
                            FROM C##BAITHIHTTT3.PHANCONG
                            GROUP BY MACB);
------7
SELECT CB.MACB, CB.MAHANG, CB.XUATPHAT, CB.DIEMDEN, CB.BATDAU, CB.TGBAY
FROM C##BAITHIHTTT3.HANGHANGKHONG HHK JOIN C##BAITHIHTTT3.CHUYENBAY CB ON HHK.MAHANG = CB.MAHANG
                    JOIN C##BAITHIHTTT3.PHANCONG PC ON PC.MACB = CB.MACB
WHERE CB.XUATPHAT = 'Đà Nẵng'
GROUP BY CB.MACB, CB.MAHANG, CB.XUATPHAT, CB.DIEMDEN, CB.BATDAU, CB.TGBAY
HAVING COUNT(PC.MANV) < 2;
/*
SELECT COUNT(PC.MANV)
FROM (SELECT MACB, MAHANG 
        FROM C##BAITHIHTTT3.CHUYENBAY
        WHERE XUATPHAT = 'Đà Nẵng') CB
        JOIN C##BAITHIHTTT3.PHANCONG PC ON PC.MACB = CB.MACB
GROUP BY CB.MAHANG
HAVING COUNT(PC.MANV) < 2;
*/
------8
SELECT *
FROM C##BAITHIHTTT3.NHANVIEN NV
WHERE  NOT EXISTS (SELECT *
                    FROM C##BAITHIHTTT3.CHUYENBAY CB
                    WHERE NOT EXISTS ( SELECT *
                                        FROM C##BAITHIHTTT3.PHANCONG PC
                                        WHERE PC.MANV = NV.MANV AND PC.MACB = CB.MACB 
                                        )
                    );

