/*
create user C##BAITHIHTTT2 identified by C##BAITHIHTTT2;
grant connect, resource, oem_monitor, dba to C##BAITHIHTTT2;
grant create synonym, create any table to C##BAITHIHTTT2;
*/

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

CREATE TABLE C##BAITHIHTTT2.OWNER
(
    OID VARCHAR2(3) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR2(25),
    PASS VARCHAR2(25),
    REGDAY DATE,
    NATIONALITY VARCHAR2(100)
);
INSERT INTO C##BAITHIHTTT2.OWNER(OID, USERNAME, PASS, REGDAY, NATIONALITY)
VALUES('001', 'faptv', '123456abc', TO_DATE('01/01/2014','DD/MM/YYYY'), 'Việt Nam');
INSERT INTO C##BAITHIHTTT2.OWNER(OID, USERNAME, PASS, REGDAY, NATIONALITY)
VALUES('002', 'kemxoitv', '@147869iii', TO_DATE('05/06/2015', 'DD/MM/YYYY'), 'Campuchia');
INSERT INTO C##BAITHIHTTT2.OWNER(OID, USERNAME, PASS, REGDAY, NATIONALITY)
VALUES('003', 'openshare', 'qwertyuiop', TO_DATE('12/05/2009', 'DD/MM/YYYY'), 'Việt Nam');

CREATE TABLE C##BAITHIHTTT2.CHANNEL
(
    CHANNELID VARCHAR2(4) NOT NULL PRIMARY KEY,
    CNAME VARCHAR2(50),
    SUBSCRIBES NUMBER,
    OID VARCHAR2(3),
    CREATED DATE
);
INSERT INTO C##BAITHIHTTT2.CHANNEL(CHANNELID, CNAME, SUBSCRIBES, OID, CREATED)
VALUES('C120', 'FAP TV', 2343, '001', TO_DATE('02/01/2014', 'DD/MM/YYYY'));
INSERT INTO C##BAITHIHTTT2.CHANNEL(CHANNELID, CNAME, SUBSCRIBES, OID, CREATED)
VALUES('C905', 'Kem xôi TV', 1032, '002', TO_DATE('09/07/2015', 'DD/MM/YYYY'));
INSERT INTO C##BAITHIHTTT2.CHANNEL(CHANNELID, CNAME, SUBSCRIBES, OID, CREATED)
VALUES('C357', 'OpenShare Cafe', 5064, '003', TO_DATE('10/12/2010', 'DD/MM/YYYY'));

CREATE TABLE C##BAITHIHTTT2.VIDEO
(
    VIDEOID VARCHAR2(7) NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(100),
    DURATION NUMBER,
    AGE NUMBER
);
INSERT INTO C##BAITHIHTTT2.VIDEO(VIDEOID, TITLE, DURATION, AGE)
VALUES('V100229', 'FAPtv Cơm Nguội Tập 41 - Đột Nhập', 469, 18);
INSERT INTO C##BAITHIHTTT2.VIDEO(VIDEOID, TITLE, DURATION, AGE)
VALUES('V211002', 'Kem xôi: Tập 31 - Mẩy Kool tình yêu của anh', 312, 16);
INSERT INTO C##BAITHIHTTT2.VIDEO(VIDEOID, TITLE, DURATION, AGE)
VALUES('V400002', 'Nơi tình yêu kết thúc - Hoàng Tuấn', 378, 0);

CREATE TABLE C##BAITHIHTTT2.SHARE_ALL
(
    VIDEOID VARCHAR2(7) NOT NULL,
    CHANNELID VARCHAR2(4) NOT NULL,
        CONSTRAINT S_PK PRIMARY KEY(VIDEOID, CHANNELID)
);
INSERT INTO C##BAITHIHTTT2.SHARE_ALL(VIDEOID, CHANNELID)
VALUES('V100229', 'C905');
INSERT INTO C##BAITHIHTTT2.SHARE_ALL(VIDEOID, CHANNELID)
VALUES('V211002', 'C120');
INSERT INTO C##BAITHIHTTT2.SHARE_ALL(VIDEOID, CHANNELID)
VALUES('V400002', 'C357');

------KHOANGOAI
ALTER TABLE C##BAITHIHTTT2.CHANNEL
ADD CONSTRAINT CH_FK FOREIGN KEY(OID) REFERENCES C##BAITHIHTTT2.OWNER(OID);
ALTER TABLE C##BAITHIHTTT2.SHARE_ALL
ADD CONSTRAINT SA_FK_1 FOREIGN KEY (VIDEOID) REFERENCES C##BAITHIHTTT2.VIDEO (VIDEOID);
ALTER TABLE C##BAITHIHTTT2.SHARE_ALL
ADD CONSTRAINT SA_FK_2 FOREIGN KEY (CHANNELID) REFERENCES C##BAITHIHTTT2.CHANNEL (CHANNELID);  

------3
CREATE OR REPLACE TRIGGER TRIGGER_CAU3
BEFORE INSERT ON C##BAITHIHTTT2.OWNER
FOR EACH ROW
BEGIN
    :NEW.REGDAY := SYSDATE;
END;
------4
CREATE OR REPLACE TRIGGER C##BAITHIHTTT2.TRIGGER_CAU4
BEFORE INSERT OR UPDATE OF CREATED ON C##BAITHIHTTT2.CHANNEL
FOR EACH ROW
DECLARE
    NGAY_DANG_KY DATE;
BEGIN
    SELECT REGDAY INTO NGAY_DANG_KY
    FROM C##BAITHIHTTT2.OWNER
    WHERE OID = :NEW.OID;
    
    IF TRUNC(:NEW.CREATED) < TRUNC(NGAY_DANG_KY) THEN
        BEGIN
            DBMS_OUTPUT.PUT_LINE('Ngày tạo kênh phảo lớn hơn hoặc bằng ngày đăng ký của người dùng sở hữu kênh đó');
        END;
    END IF;
    EXCEPTION WHEN OTHERS THEN
        BEGIN
            DBMS_OUTPUT.PUT_LINE('Error');
        END;
END;
------5
SELECT *
FROM C##BAITHIHTTT2.VIDEO 
WHERE AGE >= 16;
------6
SELECT *
FROM C##BAITHIHTTT2.CHANNEL
WHERE SUBSCRIBES = (SELECT MAX(SUBSCRIBES) 
                    FROM C##BAITHIHTTT2.CHANNEL);
------7
SELECT V.VIDEOID, COUNT(S.CHANNELID)
FROM C##BAITHIHTTT2.SHARE_ALL S JOIN C##BAITHIHTTT2.VIDEO V ON V.VIDEOID = S.VIDEOID
WHERE AGE >=18
GROUP BY V.VIDEOID;
------8
SELECT *
FROM C##BAITHIHTTT2.VIDEO V
WHERE NOT EXISTS (SELECT *
                    FROM C##BAITHIHTTT2.CHANNEL C
                    WHERE NOT EXISTS(   SELECT *
                                        FROM C##BAITHIHTTT2.SHARE_ALL SA
                                        WHERE V.VIDEOID = SA.VIDEOID AND SA.CHANNELID = C.CHANNELID
                                        )
                    );