CREATE USER C##BAITHIHTTT3 IDENTIFIED BY C##BAITHIHTTT3;
GRANT CONNECT,RESOURCE, DBA TO C##BAITHIHTTT3;
GRANT CREATE ANY TABLE TO C##BAITHIHTTT3;

CREATE TABLE C##BAITHIHTTT3.HANGHANGKHONG
(
    MAHANG VARCHAR2(2) NOT NULL,
    TENHANG VARCHAR2(50),
    NGTL DATE NOT NULL,
    DUONGBAY NUMBER,
    CONSTRAINT PK_HHK PRIMARY KEY (MAHANG)
);
CREATE TABLE C##BAITHIHTTT3.CHUYENBAY
(
    MACB VARCHAR2(5) NOT NULL,
    MAHANG VARCHAR2(4),
    XUATPHAT VARCHAR2(100) NOT NULL,
    DIEMDEN VARCHAR2(100) NOT NULL,
    BATDAU TIMESTAMP NOT NULL,
    TGBAY NUMBER ,
    CONSTRAINT PK_CB PRIMARY KEY (MACB)
);
CREATE TABLE C##BAITHIHTTT3.NHANVIEN
(
    MANV VARCHAR(4) NOT NULL,
    HOTEN VARCHAR2(50) NOT NULL,
    GIOITINH VARCHAR2(5),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR(30),
    CONSTRAINT PK_NV PRIMARY KEY(MANV)
);
CREATE TABLE C##BAITHIHTTT3.PHANCONG
(
    MACB VARCHAR2(5) NOT NULL,
    MANV VARCHAR2(5) NOT NULL,
    NHIEMVU VARCHAR2(30),
    CONSTRAINT PK_PC PRIMARY KEY (MACB, MANV)
);
ALTER TABLE C##BAITHIHTTT3.CHUYENBAY ADD CONSTRAINT FK_CB FOREIGN KEY (MAHANG) REFERENCES C##BAITHIHTTT3.HANGHANGKHONG(MAHANG);
ALTER TABLE C##BAITHIHTTT3.PHANCONG ADD CONSTRAINT FK1_PC FOREIGN KEY (MACB) REFERENCES C##BAITHIHTTT3.CHUYENBAY (MACB);
ALTER TABLE C##BAITHIHTTT3.PHANCONG ADD CONSTRAINT FK2_PC FOREIGN KEY (MANV) REFERENCES C##BAITHIHTTT3.NHANVIEN (MANV);

INSERT INTO C##BAITHIHTTT3.HANGHANGKHONG(MAHANG, TENHANG, NGTL, DUONGBAY)
VALUES('VN', 'Vietnam Airlines', TO_DATE('15/01/1956','DD/MM/YYYY'), 52);
INSERT INTO C##BAITHIHTTT3.HANGHANGKHONG(MAHANG, TENHANG, NGTL, DUONGBAY)
VALUES('VJ', 'Vietjet Air', TO_DATE('25/12/2011', 'DD/MM/YYYY'), 33);
INSERT INTO C##BAITHIHTTT3.HANGHANGKHONG(MAHANG, TENHANG, NGTL, DUONGBAY)
VALUES('BL', 'Jetstar Pacific Airlines', TO_dATE('01/12/1990', 'DD/MM/YYYY'), 13);

INSERT INTO C##BAITHIHTTT3.CHUYENBAY (MACB, MAHANG, XUATPHAT, DIEMDEN, BATDAU, TGBAY)
VALUES('VN550', 'VN', 'TP.HCM', 'Singapore', TIMESTAMP '2015-12-20 13:15:00', 2);
INSERT INTO C##BAITHIHTTT3.CHUYENBAY (MACB, MAHANG, XUATPHAT, DIEMDEN, BATDAU, TGBAY)
VALUES ('VJ331', 'VJ', '?à N?ng', 'Vinh', TIMESTAMP '2015-12-28 22:30:00', 1);
INSERT INTO C##BAITHIHTTT3.CHUYENBAY (MACB, MAHANG, XUATPHAT, DIEMDEN, BATDAU, TGBAY)
VALUES ('BL696', 'BL', 'TP. HCM', '?à L?t', TIMESTAMP '2015-12-24 06:00:00', 0.5);

INSERT INTO C##BAITHIHTTT3.NHANVIEN(MANV, HOTEN, GIOITINH, NGSINH, NGVL, CHUYENMON)
VALUES('NV01', 'Lâm V?n B?n', 'Nam', TO_DATE('10/09/1978', 'DD/MM/YYYY'), TO_DATE('05/06/2000', 'DD/MM/YYYY'), 'Phi công');
INSERT INTO C##BAITHIHTTT3.NHANVIEN(MANV, HOTEN, GIOITINH, NGSINH, NGVL, CHUYENMON)
VALUES('NV02', 'D??ng Th? L?c', 'N?', TO_DATE('22/03/1989', 'DD/MM/YYYY'), TO_DATE('12/11/2013', 'DD/MM/YYYY'), 'Ti?p viên');
INSERT INTO C##BAITHIHTTT3.NHANVIEN(MANV, HOTEN, GIOITINH, NGSINH, NGVL, CHUYENMON)
VALUES('NV03', 'Hoàng Thanh Tùng', 'Nam', TO_DATE('29/07/1983', 'DD/MM/YYYY'), TO_DATE('11/04/2007', 'DD/MM/YYYY'), 'Ti?p viên');

INSERT INTO C##BAITHIHTTT3.PHANCONG(MACB, MANV, NHIEMVU)
VALUES('VN550', 'NV01', 'C? tr??ng');
INSERT INTO C##BAITHIHTTT3.PHANCONG(MACB, MANV, NHIEMVU)
VALUES('VN550', 'NV02', 'Ti?p viên');
INSERT INTO C##BAITHIHTTT3.PHANCONG(MACB, MANV, NHIEMVU)
VALUES('BL696', 'NV03', 'Ti?p viên tr??ng');



--CAU 3  Chuyên môn c?a nhân viên ch? ???c nh?n giá tr? là ‘Phi công’ ho?c ‘Ti?p viên’.
ALTER TABLE C##BAITHIHTTT3.NHANVIEN ADD CONSTRAINT CH_NV CHECK ( CHUYENMON IN ('Phi công','Ti?p viên'));

--CAU 4 Ngày b?t ??u chuy?n bay luôn l?n h?n ngày thành l?p hãng 
--hàng không qu?n lý chuy?n bay ?ó
CREATE OR REPLACE TRIGGER C##BAITHIHTTT3.TR_CB
BEFORE INSERT OR UPDATE ON C##BAITHIHTTT3.CHUYENBAY
FOR EACH ROW
DECLARE 
    NG_TL HANGHANGKHONG.NGTL%TYPE;
    BEGIN 
        SELECT NGTL INTO NG_TL FROM C##BAITHIHTTT3.HANGHANGKHONG
        WHERE MAHANG = :NEW.MAHANG;
        IF TO_DATE (NG_TL,'DD/MM/YYYY') > TO_DATE (:NEW.BATDAU) THEN
        BEGIN
             DBMS_OUTPUT.PUT_LINE('ERROR');
        END;
        END IF;
    END;
    
--CAU 5 Tìm t?t c? các nhân viên có sinh nh?ttrong tháng 07
SELECT MANV FROM C##BAITHIHTTT3.NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH) = 7;
--GROUP BY MANV;
--CAU 6 Tìm chuy?n bay có s? nhân viên nhi?u nh?t.
SELECT C##BAITHIHTTT3.CHUYENBAY. MACB FROM C##BAITHIHTTT3.CHUYENBAY, C##BAITHIHTTT3.PHANCONG
WHERE C##BAITHIHTTT3.CHUYENBAY.MACB = C##BAITHIHTTT3.PHANCONG.MACB
GROUP BY C##BAITHIHTTT3.CHUYENBAY.MACB 
HAVING COUNT (MANV) >= ALL( SELECT COUNT(MANV)
                            FROM  C##BAITHIHTTT3.PHANCONG
                            GROUP BY MACB);
--CAU 7 V?i m?ihãng hàng không, th?ng kê s? chuy?n bay có ?i?m xu?t phát là ‘?à N?ng’ và có s? 
--nhân viên ???c phân công ít h?n 2.
SELECT CB.MACB
FROM C##BAITHIHTTT3.HANGHANGKHONG HK , C##BAITHIHTTT3.CHUYENBAY CB , C##BAITHIHTTT3.PHANCONG PC 
WHERE CB.XUATPHAT = '?à N?ng' AND HK.MAHANG=CB.MAHANG AND CB.MACB = PC.MACB
GROUP BY CB.MACB
HAVING COUNT(PC.MANV) < 2;
--CAU 8 Tìm nhân viên ???c phân công tham gia t?t c? các chuy?n bay.
SELECT * FROM C##BAITHIHTTT3.NHANVIEN NV
WHERE  NOT EXISTS (SELECT *
                    FROM C##BAITHIHTTT3.CHUYENBAY CB
                    WHERE NOT EXISTS( SELECT *
                                        FROM  C##BAITHIHTTT3.PHANCONG PC
                                        WHERE NV.MANV=PC.MANV AND CB.MACB=PC.MACB ));