CREATE USER C##BAITHIHTTT1 IDENTIFIED BY C##BAITHIHTTT1;
GRANT CONNECT,RESOURCE, DBA TO C##BAITHIHTTT1;
GRANT CREATE ANY TABLE TO C##BAITHIHTTT1;

CREATE TABLE C##BAITHIHTTT1.TUYEN(
    MATUYEN VARCHAR2(4) NOT NULL,
    BENDAU VARCHAR2(3) NOT NULL,
    BENCUOI VARCHAR2(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK INT,
    CONSTRAINT PK_TUYEN PRIMARY KEY (MATUYEN)
);

CREATE TABLE C##BAITHIHTTT1.XE (
    MAXE VARCHAR(3) NOT NULL,
    BIENKS VARCHAR(10),
    MATUYEN VARCHAR (4) NOT NULL,
    SOGHET1 NUMBER,
    SOGHET2 NUMBER,
    CONSTRAINT PK_XE PRIMARY KEY (MAXE)
   );
 
CREATE TABLE C##BAITHIHTTT1.KHACH(
    MAHK VARCHAR2(4) NOT NULL,
    HOTEN VARCHAR2(100),
    GIOITINH VARCHAR2(5),
    CMND NUMBER,
    CONSTRAINT PK_KHACH PRIMARY KEY (MAHK)
);

CREATE TABLE C##BAITHIHTTT1.VEXE(
    MATUYEN VARCHAR2(4)NOT NULL,
    MAHK VARCHAR2(4) NOT NULL,
    NGMUA DATE NOT NULL,
    GIAVE DECIMAL,
    CONSTRAINT PK_VX PRIMARY KEY (MATUYEN, MAHK, NGMUA)
    
);
ALTER TABLE C##BAITHIHTTT1.XE ADD CONSTRAINT FK_XE FOREIGN KEY (MATUYEN) REFERENCES C##BAITHIHTTT1.TUYEN (MATUYEN);
ALTER TABLE C##BAITHIHTTT1.VEXE ADD CONSTRAINT FK1_VX FOREIGN KEY (MATUYEN) REFERENCES   C##BAITHIHTTT1.TUYEN(MATUYEN);
ALTER TABLE C##BAITHIHTTT1.VEXE ADD CONSTRAINT FK2_VX FOREIGN KEY (MAHK) REFERENCES C##BAITHIHTTT1.KHACH(MAHK);

INSERT INTO C##BAITHIHTTT1.XE ( MAXE, BIENKS, MATUYEN, SOGHET1, SOGHET2) 
VALUES ( 'X01', '52LD-4393', 'T11A', '20', '20');
INSERT INTO C##BAITHIHTTT1.XE ( MAXE, BIENKS, MATUYEN, SOGHET1, SOGHET2) 
VALUES ( 'X02', '59LD-7247', 'T32D', '36', '36');
INSERT INTO C##BAITHIHTTT1.XE ( MAXE, BIENKS, MATUYEN, SOGHET1, SOGHET2) 
VALUES ( 'X03', '59LD-6850', 'T06F', '15', '15');

INSERT INTO C##BAITHIHTTT1.TUYEN(MATUYEN, BENDAU, BENCUOI, GIATUYEN, NGXB, TGDK)
VALUES ('T11A', 'SG', 'DL', 210000, TO_DATE('26/12/2016','DD/MM/YYYY'), 6);
INSERT INTO C##BAITHIHTTT1.TUYEN(MATUYEN, BENDAU, BENCUOI, GIATUYEN, NGXB, TGDK)
VALUES ('T32D', 'PT', 'SG', 120000, TO_DATE('30/12/2016','DD/MM/YYYY'), 4);
INSERT INTO C##BAITHIHTTT1.TUYEN(MATUYEN, BENDAU, BENCUOI, GIATUYEN, NGXB, TGDK)
VALUES ('T06F', 'NT', 'DNG', 225000, TO_DATE('02/01/2017', 'DD/MM/YYYY'), 7);

INSERT INTO C##BAITHIHTTT1.KHACH(MAHK, HOTEN, GIOITINH, CMND)
VALUES('KH01', 'Lâm V?n B?n', 'Nam', '655615896');
INSERT INTO C##BAITHIHTTT1.KHACH(MAHK, HOTEN, GIOITINH, CMND)
VALUES('KH02', 'D??ng Th? L?c', 'N?', '2756486426');
INSERT INTO C##BAITHIHTTT1.KHACH(MAHK, HOTEN, GIOITINH, CMND)
VALUES('KH03', 'Hoàng Thanh Tùng', 'Nam', '456889143');


INSERT INTO C##BAITHIHTTT1.VEXE(MATUYEN, MAHK, NGMUA, GIAVE)
VALUES('T11A', 'KH01', TO_DATE('20/12/2016', 'DD/MM/YYYY'), 210000);
INSERT INTO C##BAITHIHTTT1.VEXE(MATUYEN, MAHK, NGMUA, GIAVE)
VALUES('T32D', 'KH02', TO_DATE('25/12/2016', 'DD/MM/YYYY'), 144000);
INSERT INTO C##BAITHIHTTT1.VEXE(MATUYEN, MAHK, NGMUA, GIAVE)
VALUES('T06F', 'KH03', TO_DATE('30/12/2016', 'DD/MM/YYYY'), 270000);
---Thêm vào ?? check truy v?n
INSERT INTO C##BAITHIHTTT1.VEXE(MATUYEN, MAHK, NGMUA, GIAVE)
VALUES('T06F', 'KH02', TO_DATE('30/12/2016', 'DD/MM/YYYY'), 270000);



----CAU 3 Các tuy?n xe có Th?i gian d? ki?n l?n h?n 5 ti?ng luôn có giá tuy?n l?n h?n 200.000.
ALTER TABLE C##BAITHIHTTT1.TUYEN 
ADD CONSTRAINT CHECK_TGDK 
CHECK ( TGDK > 5 AND GIATUYEN >200000);

---CAU 4  Tuy?n xe có ngày xu?t b?n t? ngày 29/12/2016 ??n ngày 
--05/01/2017 s? có giá vé t?ng 20%.
CREATE OR REPLACE TRIGGER C##BAITHIHTTT1.TR_TX_VX 
BEFORE INSERT OR UPDATE ON C##BAITHIHTTT1.VEXE
FOR EACH ROW
DECLARE
NG_XB TUYEN.NGXB%TYPE;
GIA_TUYEN TUYEN.GIATUYEN%TYPE;
BEGIN 
    SELECT NGXB, GIATUYEN INTO NG_XB, GIA_TUYEN FROM C##BAITHIHTTT1.TUYEN
    WHERE MATUYEN = :NEW.MATUYEN;
    IF TO_DATE(NG_XB, 'DD/MM/YYYY') > = TO_DATE('29/12/2016', 'DD/MM/YYYY') AND TO_DATE(NG_XB, 'DD/MM/YYYY') <=TO_DATE('05/01/2017', 'DD/MM/YYYY')
    THEN BEGIN
       :NEW.GIAVE :=  GIA_TUYEN + (GIA_TUYEN * 0.2);
       END;
    END IF;
END;

---CAU 5 Tìm t?t c? các vé xe mua trong tháng 12, s?p x?p k?t qu? gi?m d?n theo giá vé.
SELECT * FROM C##BAITHIHTTT1.VEXE
WHERE  EXTRACT(MONTH FROM NGMUA) = 12 
ORDER BY GIAVE DESC;

---CAU 6 Tìm tuy?n xe có s? vé xe ít nh?t trong n?m 2016.
SELECT MATUYEN FROM C##BAITHIHTTT1.VEXE 
WHERE EXTRACT(YEAR FROM NGMUA)=2016
GROUP BY MATUYEN
HAVING COUNT (MATUYEN)<= ALL ( SELECT COUNT(MATUYEN) FROM C##BAITHIHTTT1.VEXE
                                WHERE EXTRACT(YEAR FROM NGMUA)=2016
                                GROUP BY MATUYEN);
--- CAU 7 Tìm tuy?n xe có c? hành khách nam và hành khách n? mua vé.
SELECT MATUYEN FROM C##BAITHIHTTT1.VEXE 
JOIN C##BAITHIHTTT1.KHACH ON C##BAITHIHTTT1.VEXE.MAHK = C##BAITHIHTTT1.KHACH.MAHK 
WHERE KHACH.GIOITINH ='Nam'
INTERSECT
SELECT MATUYEN FROM C##BAITHIHTTT1.VEXE 
JOIN C##BAITHIHTTT1.KHACH ON C##BAITHIHTTT1.VEXE.MAHK = C##BAITHIHTTT1.KHACH.MAHK 
WHERE C##BAITHIHTTT1.KHACH.GIOITINH ='N?';
--- CAU 8 Tìm hành khách n? ?ã t?ng mua vé t?t c? các tuy?n xe.
SELECT * FROM C##BAITHIHTTT1.KHACH
WHERE GIOITINH = 'N?' AND NOT EXISTS (SELECT * FROM C##BAITHIHTTT1.TUYEN 
                                        WHERE NOT EXISTS( SELECT * FROM C##BAITHIHTTT1.VEXE 
                                                            WHERE C##BAITHIHTTT1.TUYEN.MATUYEN = C##BAITHIHTTT1.TUYEN.MATUYEN AND C##BAITHIHTTT1.KHACH.MAHK = C##BAITHIHTTT1.KHACH.MAHK ));
                                                        
                                    

